if (GetLocale() == "koKR") then
	-- Buttons and Titles
	PERL_LOCALIZED_CONFIG_ALL = "전체";
	PERL_LOCALIZED_CONFIG_ARCANEBAR = "시전바";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY = "전투상황";
	PERL_LOCALIZED_CONFIG_FOCUS = "주시";
	PERL_LOCALIZED_CONFIG_FOCUSTARGET = "주시 대상";
	PERL_LOCALIZED_CONFIG_FOCUSPARTYTARGET = "주시/파티원 대상";
	PERL_LOCALIZED_CONFIG_PARTY = "파티원";
	PERL_LOCALIZED_CONFIG_PARTYPET = "파티원 소환수";
	PERL_LOCALIZED_CONFIG_PARTYTARGET = "파티원 대상";
	PERL_LOCALIZED_CONFIG_PLAYER = "플레이어";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF = "플레이어 버프";
	PERL_LOCALIZED_CONFIG_PLAYERPET = "플레이어 소환수";
	PERL_LOCALIZED_CONFIG_TARGET = "대상";
	PERL_LOCALIZED_CONFIG_TARGETTARGET = "대상의 대상";

	-- Perl Config Shared Strings
	PERL_LOCALIZED_CONFIG_TRANSPARENCY = "투명도";
	PERL_LOCALIZED_CONFIG_SCALING = "크기 조절";
	PERL_LOCALIZED_CONFIG_SCALING_SET_CURRENT = "현재 UI 크기로 설정";
	PERL_LOCALIZED_CONFIG_MISC = "기타";
	PERL_LOCALIZED_CONFIG_DISPLAY_MODE = "표시 형태";
	PERL_LOCALIZED_CONFIG_DRUIDBAR = "Druid Bar 지원";
	PERL_LOCALIZED_CONFIG_RESET_FRAMES = "창 위치 초기화";
	PERL_LOCALIZED_CONFIG_PORTRAITS = "초상화 창 표시";
	PERL_LOCALIZED_CONFIG_THREED_PORTRAITS = "3D 초상화 창";
	PERL_LOCALIZED_CONFIG_ALWAYS_SHOWN = "항상 표시";
	PERL_LOCALIZED_CONFIG_HIDDEN_IN_RAID = "공격대시 숨김";
	PERL_LOCALIZED_CONFIG_ALWAYS_HIDDEN = "항상 숨김";
	PERL_LOCALIZED_CONFIG_BUFF_LOCATION = "버프 위치";
	PERL_LOCALIZED_CONFIG_DEBUFF_LOCATION = "디버프 위치";
	PERL_LOCALIZED_CONFIG_BUFF_SIZE_SMALL = "버프 크기 (기본값 : 12)";
	PERL_LOCALIZED_CONFIG_DEBUFF_SIZE_SMALL = "디버프 크기 (기본값 : 12)";
	PERL_LOCALIZED_CONFIG_BUFF_SIZE_LARGE = "버프 크기 (기본값 : 16)";
	PERL_LOCALIZED_CONFIG_DEBUFF_SIZE_LARGE = "디버프 크기 (기본값 : 16)";
	PERL_LOCALIZED_CONFIG_BUFF_NUMBER = "버프의 #";
	PERL_LOCALIZED_CONFIG_DEBUFF_NUMBER = "디버프의 #";
	PERL_LOCALIZED_CONFIG_COMBAT_TEXT = "전투 수치";
	PERL_LOCALIZED_CONFIG_COMPACT = "조밀한 형태";
	PERL_LOCALIZED_CONFIG_DISPLAY_PERCENTS = "백분율 표시";
	PERL_LOCALIZED_CONFIG_SHORT_BARS = "짧은 바 형태";
	PERL_LOCALIZED_CONFIG_VERTICAL_FRAMES = "수직으로 창 표시";
	PERL_LOCALIZED_CONFIG_HIDE_CLASSICON_FRAME = "직업 아이콘 창";
	PERL_LOCALIZED_CONFIG_HEALER_MODE = "치유사 형태";
	PERL_LOCALIZED_CONFIG_PET_SUPPORT = "소환수 바 표시";
	PERL_LOCALIZED_CONFIG_CLASS_COLORED_NAMES = "색상화된 직업별 이름";
	PERL_LOCALIZED_CONFIG_SMALL = "작게";
	PERL_LOCALIZED_CONFIG_BIG = "크게";
	PERL_LOCALIZED_CONFIG_HIDE_POWER_BARS = "마나/기력/분노 바 숨김";
	PERL_LOCALIZED_CONFIG_DISPLAY_MANA_DEFICIT = "마나 결손치 표시"
	PERL_LOCALIZED_CONFIG_PVP_STATUS_ICON = "PvP 상태 아이콘";
	PERL_LOCALIZED_CONFIG_SHOW_BAR_VALUES = "실제 수치 표시";
	PERL_LOCALIZED_CONFIG_INVERT_BAR_VALUES = "실제 수치 반전 표시";
	PERL_LOCALIZED_CONFIG_COLOR_FRAME_DEBUFF = "디버프에 따른 색상 창";
	PERL_LOCALIZED_CONFIG_CLASS_BUFF = "직업 버프만";
	PERL_LOCALIZED_CONFIG_CLASS_DEBUFF = "해제할 수 있는 디버프만";
	PERL_LOCALIZED_CONFIG_ALIGN_HORIZONTALLY = "수평 정렬";
	PERL_LOCALIZED_CONFIG_THREAT_ICONS = "위협 수준 아이콘";
	PERL_LOCALIZED_CONFIG_MY_DEBUFFS = "나의 디버프만"

	-- Perl Config Generic
	PERL_LOCALIZED_CONFIG_HEADER = "Perl 설정";
	PERL_LOCALIZED_CONFIG_CLOSE = "닫기";
	PERL_LOCALIZED_CONFIG_NOTINSTALLED = "설치되지 않음";
	PERL_LOCALIZED_CONFIG_NOTINSTALLED_EXPLANATION = "애드온이 설치되어 있지 않거나 활성화되지 않았습니다.";

	-- Perl Config All
	PERL_LOCALIZED_CONFIG_ALL_TEXTURED_BARS = "바 텍스쳐";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_ONE = "텍스쳐 #1";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_TWO = "텍스쳐 #2";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_THREE = "텍스쳐 #3";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_FOUR = "텍스쳐 #4";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_FIVE = "텍스쳐 #5";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_SIX = "텍스쳐 #6";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_NONE = "텍스쳐 없음";
	PERL_LOCALIZED_CONFIG_ALL_MINIMAP_POSITION = "미니맵 버튼 위치";
	PERL_LOCALIZED_CONFIG_ALL_SHOW_MINIMAP = "미니맵 버튼 표시";
	PERL_LOCALIZED_CONFIG_ALL_FRAMES = "창";
	PERL_LOCALIZED_CONFIG_ALL_TRANSPARENT_BACKGROUND = "창 배경 투명화";
	PERL_LOCALIZED_CONFIG_ALL_LOCK_ALL = "모든 창 잠금";
	PERL_LOCALIZED_CONFIG_ALL_UNLOCK_ALL = "모든 창 풀림";
	PERL_LOCALIZED_CONFIG_ALL_LOAD = "모든 설정 불러오기";
	PERL_LOCALIZED_CONFIG_ALL_SAVE = "모든 설정 저장";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 모든 설정을 불러옵니다.";
	PERL_LOCALIZED_CONFIG_ALL_SAVE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 모든 설정을 저장합니다.";
	PERL_LOCALIZED_CONFIG_ALL_RESET_FRAMES_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 창 위치가 초기화되었습니다.";
	PERL_LOCALIZED_CONFIG_ALL_CLICKHEALING = "CastParty/Genesis/AceHeal/ClickHeal 지원";
	PERL_LOCALIZED_CONFIG_ALL_PROGRESSIVE = "색상 변화에 따른 단계적 생명력 바";
	PERL_LOCALIZED_CONFIG_ALL_NO_PROFILE_SELECTED_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 프로화일을 선택할 수 없습니다.";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 프로화일 설정을 불러옵니다: ";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_HEADER = "불러올 프로화일";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_BUTTON = "불러오기";
	PERL_LOCALIZED_CONFIG_ALL_DELETE_PROFILE_BUTTON = "삭제하기";
	PERL_LOCALIZED_CONFIG_ALL_DELETE_PROFILE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 목록에서 프로화일 설정을 삭제합니다: ";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURED_BACKGROUND = "상태 바 배경 텍스쳐 표시";
	PERL_LOCALIZED_CONFIG_ALL_FADE_BARS = "상태 바 사라짐 효과";
	PERL_LOCALIZED_CONFIG_ALL_CLICKCASTABLE_NAME_FRAMES = "이름 창 클릭을 시전가능하게 만듬";
	PERL_LOCALIZED_CONFIG_ALL_MINIMAP_RADIUS = "미니맵 버튼 반경";
	PERL_LOCALIZED_CONFIG_ALL_POSITIONING_MODE = "위치 모드";
	PERL_LOCALIZED_CONFIG_ALL_POSITIONING_MODE_TOOLTIP = "이 옵션은 *창 위치*를 위한 옵션입니다!\n문자'errors'는 정상이며 알릴 필요가 없다.\n대상이 있다면 창의 제목은 변하지 않으며 이 옵션은 일하지 않는다.";

	-- Perl Config ArcaneBar
	PERL_LOCALIZED_CONFIG_ARCANEBAR_ENABLE = PERL_LOCALIZED_CONFIG_ARCANEBAR.." 창 활성화";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_DISPLAY_TIMER = "시전 타이머 표시";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_HIDE_BLIZZARD = "기본 캐스팅 바 숨김";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_REPLACE_NAME = "플레이어 이름을 주문 이름으로 대체";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_LEFT_TIMER = "시전 타이머 왼쪽 정렬";

	-- Perl Config CombatDisplay
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_PERSIST_MODES = "지속 형태";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_TARGET_SETTINGS = "대상 설정";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_AUTOATTACK = "자동 공격중";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_ONAGRO = "전투중";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_HEALTH_PERSIST = "생명력이 변화할 때";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_MANA_PERSIST = "마나가 변화할 때";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_MENU = "오른쪽 클릭으로 메뉴 열기";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_LOCK = PERL_LOCALIZED_CONFIG_COMBATDISPLAY.." 창 잠금";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_ENABLE_TARGET = "대상 창 활성화";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_DISPLAY_COMBOPOINT_BAR = "연계 포인트 바 표시";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_CLICK_THROUGH = "창을 통한 클릭";

	-- Perl Config Party
	PERL_LOCALIZED_CONFIG_PARTY_SPACING = "간격 (기본값 : 95)";
	PERL_LOCALIZED_CONFIG_PARTY_FKEYS = "F 단축키 표시";
	PERL_LOCALIZED_CONFIG_PARTY_LOCK = PERL_LOCALIZED_CONFIG_PARTY.." 창 잠금";
	PERL_LOCALIZED_CONFIG_PARTY_PORTRAITBUFFS = "초상화에 버프 정렬";

	-- Perl Config Party Pet
	PERL_LOCALIZED_CONFIG_PARTYPET_ENABLE = PERL_LOCALIZED_CONFIG_PARTYPET.." 창 활성화";
	PERL_LOCALIZED_CONFIG_PARTYPET_RESET_FRAMES_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": "..PERL_LOCALIZED_CONFIG_PARTYPET.." 창 위치가 초기화 되었습니다.";
	PERL_LOCALIZED_CONFIG_PARTYPET_LOCK = PERL_LOCALIZED_CONFIG_PARTYPET.." 창 잠금";

	-- Perl Config Party Target
	PERL_LOCALIZED_CONFIG_PARTYTARGET_ENABLE = PERL_LOCALIZED_CONFIG_PARTYTARGET.." 창 활성화";
	PERL_LOCALIZED_CONFIG_FOCUSTARGET_ENABLE = PERL_LOCALIZED_CONFIG_FOCUSTARGET.." 창 활성화";
	PERL_LOCALIZED_CONFIG_PARTYTARGET_LOCK = PERL_LOCALIZED_CONFIG_PARTYTARGET.." 창 잠금";
	PERL_LOCALIZED_CONFIG_PARTYTARGET_PARTY_HIDDEN_IN_RAID = PERL_LOCALIZED_CONFIG_PARTYTARGET.." "..PERL_LOCALIZED_CONFIG_HIDDEN_IN_RAID;
	PERL_LOCALIZED_CONFIG_PARTYTARGET_FOCUS_HIDDEN_IN_RAID = PERL_LOCALIZED_CONFIG_FOCUSTARGET.." "..PERL_LOCALIZED_CONFIG_HIDDEN_IN_RAID;
	PERL_LOCALIZED_CONFIG_PARTYTARGET_SCALE = PERL_LOCALIZED_CONFIG_PARTY.." "..PERL_LOCALIZED_CONFIG_TARGET.." "..PERL_LOCALIZED_CONFIG_SCALING;
	PERL_LOCALIZED_CONFIG_FOCUSTARGET_SCALE = PERL_LOCALIZED_CONFIG_FOCUS.." "..PERL_LOCALIZED_CONFIG_TARGET.." "..PERL_LOCALIZED_CONFIG_SCALING;

	-- Perl Config Player
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_MODE = "경험치 바 형태";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_EXPERIENCE = "경험치";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_PVPRANK = "PvP 등급";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_REPUTATION = "평판";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_HIDDEN = "숨김";
	PERL_LOCALIZED_CONFIG_PLAYER_RAID_GROUP = "공격대시 파티 번호 표시";
	PERL_LOCALIZED_CONFIG_PLAYER_LOCK = PERL_LOCALIZED_CONFIG_PLAYER.." 창 잠금";
	PERL_LOCALIZED_CONFIG_PLAYER_RAID_GROUP_IN_NAME = "이름 창 안에 공격대 번호 표시";
	PERL_LOCALIZED_CONFIG_PLAYER_FIVE_SECOND_RULE = "5초 룰 규칙";
	PERL_LOCALIZED_CONFIG_PLAYER_TOTEM_TIMERS = "토템 타이머";
	PERL_LOCALIZED_CONFIG_PLAYER_RUNE_FRAME = "룬 창";
	PERL_LOCALIZED_CONFIG_PLAYER_PVP_TIMER = "PvP 타이머";

	-- Perl Config Player Buff
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_ENABLE = "플레이어 창 버프 활성화";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_WARNING = "30초 주문 경고 메시지 활성화";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_HIDESECONDS = "시간 숨김";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_HORIZONTAL_SPACING = "수평 간격 (기본값 : 10)";

	-- Perl Config Player Pet
	PERL_LOCALIZED_CONFIG_PLAYERPET_EXPERIENCE = "경험치 바 활성화";
	PERL_LOCALIZED_CONFIG_PLAYERPET_LOCK = PERL_LOCALIZED_CONFIG_PLAYERPET.." 창 잠금";
	PERL_LOCALIZED_CONFIG_PLAYERPET_HIDENAME = "이름 숨김";
	PERL_LOCALIZED_CONFIG_PLAYERPET_TARGET = "소환수 대상";
	PERL_LOCALIZED_CONFIG_PLAYERPET_TARGET_ENABLE = PERL_LOCALIZED_CONFIG_PLAYERPET_TARGET.." 창 활성화";
	PERL_LOCALIZED_CONFIG_PLAYERPET_SCALE = PERL_LOCALIZED_CONFIG_PLAYERPET.." "..PERL_LOCALIZED_CONFIG_SCALING;
	PERL_LOCALIZED_CONFIG_PLAYERPET_TARGET_SCALE = PERL_LOCALIZED_CONFIG_PLAYERPET.." "..PERL_LOCALIZED_CONFIG_TARGET.." "..PERL_LOCALIZED_CONFIG_SCALING;

	-- Perl Config Target
	PERL_LOCALIZED_CONFIG_TARGET_BUFFDEBUFF_SCALING = "버프/디버프 크기 (기본값 : 100)";
	PERL_LOCALIZED_CONFIG_TARGET_COMBO_LOCATION = "연계 포인트 위치";
	PERL_LOCALIZED_CONFIG_TARGET_CLASS_ICON = "직업 아이콘";
	PERL_LOCALIZED_CONFIG_TARGET_CLASS_FRAME = "직업 창";
	PERL_LOCALIZED_CONFIG_TARGET_RARE_ELITE_FRAME = "희귀/정예 창";
	PERL_LOCALIZED_CONFIG_TARGET_HIDE_BUFFDEBUFF_BACKGROUND = "버프/디버프 배경 숨김";
	PERL_LOCALIZED_CONFIG_TARGET_SOUND_ON_TARGET_CHANGE = "대상 변경시 경고음";
	PERL_LOCALIZED_CONFIG_TARGET_LOCK = PERL_LOCALIZED_CONFIG_TARGET.." 창 잠금";
	PERL_LOCALIZED_CONFIG_TARGET_COMBO_POINT_FRAME = "연계 포인트 창";
	PERL_LOCALIZED_CONFIG_TARGET_DISPLAY_IN_NAME_FRAME = "이름 창에 연계 포인트 표시";
	PERL_LOCALIZED_CONFIG_TARGET_DEBUFF_STACKS_IN_COMBO_FRAME = "연계 포인트 창에 디버프 중첩 표시";
	PERL_LOCALIZED_CONFIG_TARGET_ALTERNATE_FRAME_STYLE = "다른 창 모양";
	PERL_LOCALIZED_CONFIG_TARGET_INVERT_BUFFS_DEBUFFS = "버프/디버프 반전";
	PERL_LOCALIZED_CONFIG_TARGET_GUILD_FRAME = "길드 이름 창";
	PERL_LOCALIZED_CONFIG_TARGET_ELITE_RARE_GRAPHIC = "정예/희귀 시각화";
	PERL_LOCALIZED_CONFIG_TARGET_BUFF_DEBUFF_TIMERS = "버프/디버프 타이머";
	PERL_LOCALIZED_CONFIG_TARGET_DISPLAY_NUMERIC_THREAT = "위협 숫자 표시";
	PERL_LOCALIZED_CONFIG_TARGET_DISPLAY_NUMERIC_THREAT_TOOLTIP = "이 옵션을 사용한다면 '"..PERL_LOCALIZED_CONFIG_TARGET_RARE_ELITE_FRAME.."' 기능을 사용할 수 없습니다.";

	-- Perl Config Target Target
	PERL_LOCALIZED_CONFIG_TARGETTARGET_MAIN = "기본 설정";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ALERT_MODE = "경고 형태";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ALERT_SIZE = "경고 크기";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ENABLE_TOT = "대상의 대상 활성화";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ENABLE_TOTOT = "대상의 대상의 대상 활성화";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_AUDIO_ALERT_ON_AGRO = "어그로 획득시 경고음";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_LOCK = PERL_LOCALIZED_CONFIG_TARGETTARGET.." 창 잠금";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOT_BUFFS = "대상의 대상 버프 표시";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOT_DEBUFFS = "대상의 대상 디버프 표시";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOTOT_BUFFS = "대상의 대상의 대상 버프 표시";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOTOT_DEBUFFS = "대상의 대상의 대상 디버프 표시";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_DPS_MODE = "DPS 형태";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TANK_MODE = "Tank 형태";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_HEALER_MODE = "Healer 형태";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SMALL_TEXT = "작은 글자";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_LARGE_TEXT = "큰 글자";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_NO_TEXT = "글자 없음";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_RIGHT_OF_TARGET_FRAME = "대상 창의 오른쪽";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TOP_OF_TARGET_FRAME = "대상 창의 위쪽";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_RIGHT_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 대상의 대상 창을 대상 창의 '오른쪽'에 위치시킵니다.";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TOP_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 대상의 대상 창을 대상 창의 '위쪽'에 위치시킵니다.";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_FRIENDLY_HEALTH = "우호적 플레이어 실제 생명력 수치 표시";
end
